name: Main Taski Workflow
on:
  push:
    branches:
      - main
jobs:
  checkout-and-print-tree:
  runs-on: ubuntu-latest
  steps:
    - name: Check out repository code
      user: actions/checkout@v3
    - name: Print project tree
      run: tree .